### ISSUE TITLE
Support for timeout and BLE address as input

### ISSUE THREAD

**Issue by guibom** [eschava/node-red-contrib-xiaomi-ble#1]
Thanks for this node! I've tested with both Flora and Temperature devices and it works great.

It would be useful if it was possible to configure the timeout for scanning, and also to be able to pass the address as an input to the node, so it's possible to automate a loop doing scans for different devices.

**Comment by eschava** [comment]
Thanks for the feedback! I'll think about address as an input but why do you need configurable scanning timeout? Isn't 60 seconds enough for any kind of devices?

**Comment by eschava** [comment]
Done. Please check v1.2.0

**Comment by guibom** [comment]
That worked perfectly, thanks!
The reason I mentioned the timeout was that I actually wanted to reduce it.

My setup is that I have about 20 flora devices, and I want to automate reading them. 
Up to now I've been using a python script. It's not a great solution, and I prefer doing it all using node-red nodes.
