### ISSUE TITLE
Does not work after upgrading Node-Red

### ISSUE THREAD

**Issue by Toshibass** [eschava/node-red-contrib-xiaomi-ble#13]
Please be advised .. this node does not work if you upgrade Node-Red to 0.20.5 which automatically installs node.js 10.15.3, I had to reverted back to Node-Red 0.19.5 & node 8.11.3 to get it to works again.

**Comment by eschava** [comment]
Please check similar issue https://github.com/eschava/node-red-contrib-xiaomi-ble/issues/4

**Comment by eschava** [comment]
Should be fixed with 1.2.4
