### ISSUE TITLE
Suggestion: Change to maintained fork of Noble library

### ISSUE THREAD

**Issue by cHemingway** [eschava/node-red-contrib-xiaomi-ble#14]
The bluetooth library [noble](https://github.com/noble/noble) has not been updated in a year,  has many open issues, and [does not work](https://github.com/noble/noble/issues/850) with the latest version of Node LTS, which Node-Red will install by default, (possibly causing this issue? https://github.com/eschava/node-red-contrib-xiaomi-ble/issues/10)

The fork [abandonware/noble](https://github.com/abandonware/noble) is actively maintained, and works with Node 10. It uses a forked version of bluetooth-hci-socket as well, which might fix this issue: https://github.com/eschava/node-red-contrib-xiaomi-ble/issues/4 .

I think the API is the same, but I don't know JS well enough to check sorry.

**Comment by eschava** [comment]
Done
