### ISSUE TITLE
installation problem on Windows 10

### ISSUE THREAD

**Issue by regissg** [eschava/node-red-contrib-xiaomi-ble#19]
I have used node red managed palette menu to install node-red-contrib-xiaomi-ble but I have an error message that seems to indicate that this file is missing: node-pre-gyp
2020-02-05T22:39:53.564Z [err]  WARN Tried to download(404): https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-4/binding-0.5.3-4-node-v72-win32-x64.tar.gz

The complete log file is attached
[2020-02-05T22_39_59_037Z-debug.log](https://github.com/eschava/node-red-contrib-xiaomi-ble/files/4162425/2020-02-05T22_39_59_037Z-debug.log)

any clue on how to fix that?

**Comment by eschava** [comment]
Could you please redirect this issue to the issue tracker of that library ( https://github.com/abandonware/node-bluetooth-hci-socket ) ?

**Comment by regissg** [comment]
I have done that and followed their instruction to run `npm install --verbose @abandonware/bluetooth-hci-socket` which seems to install ok. 
[bluetooth-hci-socket.log](https://github.com/eschava/node-red-contrib-xiaomi-ble/files/4169928/bluetooth-hci-socket.log)

I could then run `npm install node-red-contrib-xiaomi-ble` which seems to install without critical error as you could see in the log below. 
[node-red-contrib-xiaomi-ble.log](https://github.com/eschava/node-red-contrib-xiaomi-ble/files/4169930/node-red-contrib-xiaomi-ble.log)

But then when I launch node red I could not see the Xiaomi BLE node.

Am I missing something?

**Comment by eschava** [comment]
Are you sure that xiaomi-ble was installed to the same folder where node-red is?

**Comment by eschava** [comment]
Ah, sorry, I see that it is in correct place (C:\Users\regis\.node-red)
Maybe there are some errors during startup of node-red?
