### ISSUE TITLE
Moisture range?

### ISSUE THREAD

**Issue by GAZ082** [eschava/node-red-contrib-xiaomi-ble#2]
Hi there. I put my Mi Flora sensor in water and the max moist i got was 60, is this ok?

Thanks!

**Comment by eschava** [comment]
Could you please check results of Xiaomi Android/iPhone application to confirm they are same?

**Comment by GAZ082** [comment]
Hi! I tested again, put the sensor inside a glass full with water and got 63 in moisture in both, node red and Android app.

Thanks!

**Comment by GAZ082** [comment]
I know this is not a bug, but perhaps some feedback would be welcome.
