### ISSUE TITLE
"Searching" status without any outgoing information

### ISSUE THREAD

**Issue by Nazarbayevv** [eschava/node-red-contrib-xiaomi-ble#25]
Hello,

I have node-red 1.1.2 on Raspberry Pi 4B. I used node-red-contrib-xiaomi-ble 1.3.0 and it worked fine till I "apt update && apt upgrade" packeges on my Rasbian. I can see just searching status now, without any information in debug.
![image](https://user-images.githubusercontent.com/50654913/93826922-e95dd980-fc70-11ea-8ca2-2e4e56311450.png)

 From command line of my Raspberry I can see MACs of my devices.

Maybe I need downgrade any packeges? But i dont know which, Or maybe any others ideas?

**Comment by eschava** [comment]
Maybe your node.js process just lacks permissions for Bluetooth adapter access after upgrade?

**Comment by Nazarbayevv** [comment]
I updated node-red today in the evening, and It fixed issues.

**Comment by Nazarbayevv** [comment]
I updated node-red  and It fixed issues.
