### ISSUE TITLE
LYWSD03MMC error: Peripheral already connected

### ISSUE THREAD

**Issue by kobbejager** [eschava/node-red-contrib-xiaomi-ble#26]
Recently, I added 4 square temperature and humidity sensors (LYWSD03MMC) to my setup with 2 older round sensors. This works well for a while, but after some time, the LYWSD03MMC nodes go one by one into an error state "Peripheral already connected". In a couple of hours, I loose connection to all square sensors, while the older round sensors continue to work. 

Restarting my raspberry pi seems to be the only trick to make them work again. For a short while...

**Comment by kobbejager** [comment]
b108's fork seems to have a [patch for this error](https://github.com/b108/node-red-contrib-xiaomi-ble/commit/a607db92fc57b08a729fd57523b4371b89d111bb). I'm going to apply this and give it a try.

**Comment by eschava** [comment]
Wow, please keep me posted!

**Comment by kobbejager** [comment]
My sensors have been working flawlessly for a couple of days now. It seems that this patch has solved the issue.

**Comment by eschava** [comment]
Thanks, will integrate it

**Comment by eschava** [comment]
Done, 1.3.1 version released with it

**Comment by talkleasy** [comment]
Thanks for sorting. Works for me as well.
