### ISSUE TITLE
Negative temperatures issue?

### ISSUE THREAD

**Issue by kupo2kupo** [eschava/node-red-contrib-xiaomi-ble#27]
Hi, I installed your great node today, but as soon as the temperature dropped to below 0 degree Centigrade I received the following message: "Incorrect data: T=-1.9 H=35.1". Could there be something in the code that does not like negative temperatures?

**Comment by kupo2kupo** [comment]
I am using model LYWSDCGQ/01ZM which supports "The temperature range: -9.9 ℃ ~ 60 ℃".

**Comment by eschava** [comment]
Published 1.3.2 with negative temperature support

**Comment by kupo2kupo** [comment]
Great, thanks!
