### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by exitte** [eschava/node-red-contrib-xiaomi-ble#3]
Hi,
Today I checked my NodeRed flows and the element "Xiaomi BLE" is marked as unknown and package dissapeared from pallet. When I try to install it back agian (even though it's still in the folder  with modules) I get this error in error log:
" error Could not install from "node_modules/node-red-contrib-xiaomi-ble" as it does not contain a package.json file. "
What might be the problem?
BR,

**Comment by eschava** [comment]
Sorry, no idea
As you can see package.json is present in the sources

**Comment by exitte** [comment]
Hi,
I wasn't able to uninstall the package because of to many links so I just removed it and then installed, now it works. Just strange it crashed. If it happens again I'll collect some logs.
BR,
