### ISSUE TITLE
Error on use

### ISSUE THREAD

**Issue by borpin** [eschava/node-red-contrib-xiaomi-ble#4]
I am getting an error 
```
 - node-red-contrib-xiaomi-ble:Xiaomi BLE : Error: Cannot find module 'bluetooth-hci-socket'
```

**Comment by eschava** [comment]
What version of node.js are you using?

**Comment by borpin** [comment]
~# node -v
v11.0.0
~# npm -v
6.4.1

[edit]
I have just rebuilt from scratch (DietPi) and get the same error.

Other Bluetooth flows work as does `gatttool` from the command line.

**Comment by borpin** [comment]
There are a number of issues with this dependency installing https://github.com/noble/node-bluetooth-hci-socket/issues

I tried this as a solution https://github.com/DigitalSecurity/btlejuice/issues/15#issuecomment-397269423

I think the problem lies with `bluetooth-hci-socket` itself.

**Comment by eschava** [comment]
Thanks for your investigation!
