### ISSUE TITLE
Errors in Manage Palette

### ISSUE THREAD

**Issue by borpin** [eschava/node-red-contrib-xiaomi-ble#6]
I see this error in the manage palette view;
![image](https://user-images.githubusercontent.com/1322749/47603113-3f6f6700-d9df-11e8-85ce-78e30fb655a4.png)
Where would there be a log of this error?  There is nothing in the node-red log.  It does work though.

I am using another Bluetooth node that uses `l2ping`
![image](https://user-images.githubusercontent.com/1322749/47603165-22876380-d9e0-11e8-9eb3-6aacfc3ebb7e.png)

I am seeing a lot of these errors in the node-red log
` noble warning: unknown handle 11 disconnected!`

I managed to install this node dependency using this solution
https://github.com/noble/node-bluetooth-hci-socket/pull/91#issuecomment-403048810

**Comment by eschava** [comment]
Should be fixed with 1.2.4
